# Site settings
title: Jekyll fractal
email: youremailaddress@gmail.com
description: Just a simple, single page responsive template brought to you by HTML5 UP.
baseurl: "/fractal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: ""

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
